(function() {var implementors = {};
implementors["rustc_data_structures"] = [];implementors["rustc"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];implementors["rustc_lint"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];implementors["rustc_metadata"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];implementors["rustc_typeck"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];implementors["rustc_trans"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];implementors["rustc_borrowck"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];implementors["rustdoc"] = ["impl <a class='trait' href='rustc_data_structures/unify/trait.Combine.html' title='rustc_data_structures::unify::Combine'>Combine</a> for <a class='struct' href='rustc/infer/unify_key/struct.RegionVidKey.html' title='rustc::infer::unify_key::RegionVidKey'>RegionVidKey</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
