(function() {var implementors = {};
implementors['rustc_const_eval'] = ["impl&lt;'a, 'tcx&gt; <a class='trait' href='rustc/hir/fold/trait.Folder.html' title='rustc::hir::fold::Folder'>Folder</a> for <a class='struct' href='rustc_const_eval/check_match/struct.StaticInliner.html' title='rustc_const_eval::check_match::StaticInliner'>StaticInliner</a>&lt;'a, 'tcx&gt;",];implementors['rustc_const_eval'] = ["impl&lt;'a, 'tcx&gt; <a class='trait' href='rustc/hir/fold/trait.Folder.html' title='rustc::hir::fold::Folder'>Folder</a> for <a class='struct' href='rustc_const_eval/check_match/struct.StaticInliner.html' title='rustc_const_eval::check_match::StaticInliner'>StaticInliner</a>&lt;'a, 'tcx&gt;",];implementors['rustc_const_eval'] = ["impl&lt;'a, 'tcx&gt; <a class='trait' href='rustc/hir/fold/trait.Folder.html' title='rustc::hir::fold::Folder'>Folder</a> for <a class='struct' href='rustc_const_eval/check_match/struct.StaticInliner.html' title='rustc_const_eval::check_match::StaticInliner'>StaticInliner</a>&lt;'a, 'tcx&gt;",];implementors["rustc_const_eval"] = ["impl&lt;'a, 'tcx&gt; <a class='trait' href='rustc/hir/fold/trait.Folder.html' title='rustc::hir::fold::Folder'>Folder</a> for <a class='struct' href='rustc_const_eval/check_match/struct.StaticInliner.html' title='rustc_const_eval::check_match::StaticInliner'>StaticInliner</a>&lt;'a, 'tcx&gt;",];implementors["rustc_const_eval"] = ["impl&lt;'a, 'tcx&gt; <a class='trait' href='rustc/hir/fold/trait.Folder.html' title='rustc::hir::fold::Folder'>Folder</a> for <a class='struct' href='rustc_const_eval/check_match/struct.StaticInliner.html' title='rustc_const_eval::check_match::StaticInliner'>StaticInliner</a>&lt;'a, 'tcx&gt;",];implementors["rustc_const_eval"] = ["impl&lt;'a, 'tcx&gt; <a class='trait' href='rustc/hir/fold/trait.Folder.html' title='rustc::hir::fold::Folder'>Folder</a> for <a class='struct' href='rustc_const_eval/check_match/struct.StaticInliner.html' title='rustc_const_eval::check_match::StaticInliner'>StaticInliner</a>&lt;'a, 'tcx&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
