(function() {var implementors = {};
implementors['rustc_mir'] = ["impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/clear_dead_blocks/struct.ClearDeadBlocks.html' title='rustc_mir::transform::clear_dead_blocks::ClearDeadBlocks'>ClearDeadBlocks</a>","impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/simplify_cfg/struct.SimplifyCfg.html' title='rustc_mir::transform::simplify_cfg::SimplifyCfg'>SimplifyCfg</a>","impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/no_landing_pads/struct.NoLandingPads.html' title='rustc_mir::transform::no_landing_pads::NoLandingPads'>NoLandingPads</a>","impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/type_check/struct.TypeckMir.html' title='rustc_mir::transform::type_check::TypeckMir'>TypeckMir</a>",];implementors['rustc_mir'] = ["impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/clear_dead_blocks/struct.ClearDeadBlocks.html' title='rustc_mir::transform::clear_dead_blocks::ClearDeadBlocks'>ClearDeadBlocks</a>","impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/simplify_cfg/struct.SimplifyCfg.html' title='rustc_mir::transform::simplify_cfg::SimplifyCfg'>SimplifyCfg</a>","impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/no_landing_pads/struct.NoLandingPads.html' title='rustc_mir::transform::no_landing_pads::NoLandingPads'>NoLandingPads</a>","impl <a class='trait' href='rustc/mir/transform/trait.MirPass.html' title='rustc::mir::transform::MirPass'>MirPass</a> for <a class='struct' href='rustc_mir/transform/type_check/struct.TypeckMir.html' title='rustc_mir::transform::type_check::TypeckMir'>TypeckMir</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
