(function() {var implementors = {};
implementors["alloc"] = ["impl&lt;'a, 'b, T:&nbsp;<a class=\"trait\" href=\"core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> + <a class=\"trait\" href=\"core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;&amp;'b <a class=\"struct\" href=\"alloc/btree_set/struct.BTreeSet.html\" title=\"struct alloc::btree_set::BTreeSet\">BTreeSet</a>&lt;T&gt;&gt; for &amp;'a <a class=\"struct\" href=\"alloc/btree_set/struct.BTreeSet.html\" title=\"struct alloc::btree_set::BTreeSet\">BTreeSet</a>&lt;T&gt;",];
implementors["pulldown_cmark"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"pulldown_cmark/struct.Options.html\" title=\"struct pulldown_cmark::Options\">Options</a>",];
implementors["rustc"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc/ty/struct.TypeFlags.html\" title=\"struct rustc::ty::TypeFlags\">TypeFlags</a>","impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc/ty/struct.AdtFlags.html\" title=\"struct rustc::ty::AdtFlags\">AdtFlags</a>","impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc/ty/struct.ReprFlags.html\" title=\"struct rustc::ty::ReprFlags\">ReprFlags</a>",];
implementors["rustc_apfloat"] = ["impl&lt;S&gt; <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc_apfloat/ieee/struct.IeeeFloat.html\" title=\"struct rustc_apfloat::ieee::IeeeFloat\">IeeeFloat</a>&lt;S&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Self: <a class=\"trait\" href=\"rustc_apfloat/trait.Float.html\" title=\"trait rustc_apfloat::Float\">Float</a>,&nbsp;</span>","impl&lt;F&gt; <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc_apfloat/ppc/struct.DoubleFloat.html\" title=\"struct rustc_apfloat::ppc::DoubleFloat\">DoubleFloat</a>&lt;F&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Self: <a class=\"trait\" href=\"rustc_apfloat/trait.Float.html\" title=\"trait rustc_apfloat::Float\">Float</a>,&nbsp;</span>","impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc_apfloat/struct.Status.html\" title=\"struct rustc_apfloat::Status\">Status</a>",];
implementors["rustc_const_math"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc_const_math/struct.ConstFloat.html\" title=\"struct rustc_const_math::ConstFloat\">ConstFloat</a>","impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"enum\" href=\"rustc_const_math/enum.ConstInt.html\" title=\"enum rustc_const_math::ConstInt\">ConstInt</a>",];
implementors["rustc_llvm"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc_llvm/debuginfo/struct.DIFlags.html\" title=\"struct rustc_llvm::debuginfo::DIFlags\">DIFlags</a>",];
implementors["rustc_mir"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"rustc_mir/transform/qualify_consts/struct.Qualif.html\" title=\"struct rustc_mir::transform::qualify_consts::Qualif\">Qualif</a>",];
implementors["syntax"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"syntax/parse/parser/struct.Restrictions.html\" title=\"struct syntax::parse::parser::Restrictions\">Restrictions</a>",];
implementors["syntax_pos"] = ["impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"syntax_pos/struct.BytePos.html\" title=\"struct syntax_pos::BytePos\">BytePos</a>","impl <a class=\"trait\" href=\"core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"syntax_pos/struct.CharPos.html\" title=\"struct syntax_pos::CharPos\">CharPos</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
