(function() {var implementors = {};
implementors["std"] = ["impl&lt;T&gt; !<a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"std/sync/mpsc/struct.Receiver.html\" title=\"struct std::sync::mpsc::Receiver\">Receiver</a>&lt;T&gt;","impl&lt;T&gt; !<a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"std/sync/mpsc/struct.Sender.html\" title=\"struct std::sync::mpsc::Sender\">Sender</a>&lt;T&gt;","impl&lt;T:&nbsp;?<a class=\"trait\" href=\"std/marker/trait.Sized.html\" title=\"trait std::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"std/marker/trait.Send.html\" title=\"trait std::marker::Send\">Send</a>&gt; <a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"std/sync/struct.Mutex.html\" title=\"struct std::sync::Mutex\">Mutex</a>&lt;T&gt;","impl&lt;'a, T:&nbsp;?<a class=\"trait\" href=\"std/marker/trait.Sized.html\" title=\"trait std::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a>&gt; <a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"std/sync/struct.MutexGuard.html\" title=\"struct std::sync::MutexGuard\">MutexGuard</a>&lt;'a, T&gt;","impl <a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"std/sync/struct.Once.html\" title=\"struct std::sync::Once\">Once</a>","impl&lt;T:&nbsp;?<a class=\"trait\" href=\"std/marker/trait.Sized.html\" title=\"trait std::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"std/marker/trait.Send.html\" title=\"trait std::marker::Send\">Send</a> + <a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a>&gt; <a class=\"trait\" href=\"std/marker/trait.Sync.html\" title=\"trait std::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"std/sync/struct.RwLock.html\" title=\"struct std::sync::RwLock\">RwLock</a>&lt;T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
